#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=deploy/lib.sh
. "$SCRIPT_DIR/lib.sh"

usage() {
  cat <<'EOF'
Usage:
  sudo ./deploy/setup-nginx.sh --domain bbs.example.com [--email admin@example.com] [--no-tls]

Installs and configures nginx as a reverse proxy for pyBulletin's web UI.
Optionally obtains a TLS certificate via certbot (Let's Encrypt).

Options:
  --domain DOMAIN    Public hostname for the BBS web UI (required)
  --email  EMAIL     Email for Let's Encrypt registration (required for TLS)
  --no-tls           Configure nginx without TLS (HTTP only)
  --web-port PORT     pybulletinweb.service port to proxy (default: 8080)
  --public-port PORT  Backward-compatible alias for --web-port
  --admin-port  PORT  Backward-compatible alias for --web-port
EOF
}

DOMAIN=""
EMAIL=""
TLS=1
WEB_PORT=8080

while [ "$#" -gt 0 ]; do
  case "$1" in
    --domain)      DOMAIN="${2:-}";      shift 2 ;;
    --email)       EMAIL="${2:-}";       shift 2 ;;
    --no-tls)      TLS=0;               shift ;;
    --web-port)    WEB_PORT="${2:-}";    shift 2 ;;
    --public-port) WEB_PORT="${2:-}";    shift 2 ;;
    --admin-port)  WEB_PORT="${2:-}";    shift 2 ;;
    -h|--help)     usage; exit 0 ;;
    *)             die "unknown argument: $1" ;;
  esac
done

[ -n "$DOMAIN" ] || { usage; die "--domain is required"; }
[ "$TLS" = "1" ] && [ -z "$EMAIL" ] && { usage; die "--email is required for TLS"; }
SCHEME="http"
[ "$TLS" = "1" ] && SCHEME="https"

require_root

mgr="$(pkg_manager)" || die "no supported package manager"
case "$mgr" in
  apt)     install_packages nginx ;;
  dnf|yum) install_packages nginx ;;
esac

NGINX_CONF="/etc/nginx/conf.d/pybulletin.conf"

cat >"$NGINX_CONF" <<NGINX
# pyBulletin — generated by setup-nginx.sh
server {
    listen 80;
    server_name ${DOMAIN};

    location / {
        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }
}
NGINX

nginx -t || die "nginx config test failed"
systemctl enable nginx >/dev/null
systemctl reload-or-restart nginx

if [ "$TLS" = "1" ]; then
  case "$mgr" in
    apt)     install_packages certbot python3-certbot-nginx ;;
    dnf|yum)
      [ "$(os_id)" != "fedora" ] && { install_packages epel-release || true; }
      install_packages certbot python3-certbot-nginx
      ;;
  esac
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL"
  log "TLS certificate obtained for $DOMAIN"
fi

log "nginx configured — public UI: ${SCHEME}://${DOMAIN}/"
log "                   sysop console: ${SCHEME}://${DOMAIN}/sysop"
