#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=deploy/lib.sh
. "$SCRIPT_DIR/lib.sh"

usage() {
  cat <<'EOF'
Usage:
  sudo ./deploy/setup-nginx.sh --domain bbs.example.com [--email admin@example.com] [--no-tls]

Installs and configures nginx as a reverse proxy for pyBulletin's web UI.
Optionally obtains a TLS certificate via certbot (Let's Encrypt).
Optional admin controls apply to /sysop, /api/, and /ws. Use them for
operator-only deployments or private admin hostnames; path-only protection of
/sysop is not enough because the sysop console uses API and WebSocket routes.

Options:
  --domain DOMAIN    Public hostname for the BBS web UI (required)
  --email  EMAIL     Email for Let's Encrypt registration (required for TLS)
  --no-tls           Configure nginx without TLS (HTTP only)
  --web-port PORT     pybulletinweb.service port to proxy (default: 8080)
  --public-port PORT  Backward-compatible alias for --web-port
  --admin-port  PORT  Backward-compatible alias for --web-port
  --admin-allow CIDR  Allow this CIDR/IP to admin/API/WS paths; repeatable
  --admin-basic-auth FILE
                      Enable HTTP basic auth using this htpasswd file for
                      admin/API/WS paths
EOF
}

DOMAIN=""
EMAIL=""
TLS=1
WEB_PORT=8080
ADMIN_ALLOW=()
ADMIN_BASIC_AUTH=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --domain)      DOMAIN="${2:-}";      shift 2 ;;
    --email)       EMAIL="${2:-}";       shift 2 ;;
    --no-tls)      TLS=0;               shift ;;
    --web-port)    WEB_PORT="${2:-}";    shift 2 ;;
    --public-port) WEB_PORT="${2:-}";    shift 2 ;;
    --admin-port)  WEB_PORT="${2:-}";    shift 2 ;;
    --admin-allow) ADMIN_ALLOW+=("${2:-}"); shift 2 ;;
    --admin-basic-auth) ADMIN_BASIC_AUTH="${2:-}"; shift 2 ;;
    -h|--help)     usage; exit 0 ;;
    *)             die "unknown argument: $1" ;;
  esac
done

[ -n "$DOMAIN" ] || { usage; die "--domain is required"; }
[ "$TLS" = "1" ] && [ -z "$EMAIL" ] && { usage; die "--email is required for TLS"; }
[ -n "$ADMIN_BASIC_AUTH" ] && [ ! -f "$ADMIN_BASIC_AUTH" ] && die "admin basic auth file not found: $ADMIN_BASIC_AUTH"
SCHEME="http"
[ "$TLS" = "1" ] && SCHEME="https"

require_root

mgr="$(pkg_manager)" || die "no supported package manager"
case "$mgr" in
  apt)     install_packages nginx ;;
  dnf|yum) install_packages nginx ;;
esac

NGINX_CONF="/etc/nginx/conf.d/pybulletin.conf"

ADMIN_GUARDS=""
if [ "${#ADMIN_ALLOW[@]}" -gt 0 ]; then
  for cidr in "${ADMIN_ALLOW[@]}"; do
    [ -n "$cidr" ] || die "--admin-allow requires a CIDR/IP"
    ADMIN_GUARDS="${ADMIN_GUARDS}        allow ${cidr};
"
  done
  ADMIN_GUARDS="${ADMIN_GUARDS}        deny all;
"
fi
if [ -n "$ADMIN_BASIC_AUTH" ]; then
  ADMIN_GUARDS="${ADMIN_GUARDS}        auth_basic \"pyBulletin sysop\";
        auth_basic_user_file ${ADMIN_BASIC_AUTH};
"
fi

cat >"$NGINX_CONF" <<NGINX
# pyBulletin — generated by setup-nginx.sh
server {
    listen 80;
    server_name ${DOMAIN};

    location = /api/health {
        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    location /sysop {
${ADMIN_GUARDS}        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    location /api/ {
${ADMIN_GUARDS}        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    location /ws {
${ADMIN_GUARDS}        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    location / {
        proxy_pass         http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }
}
NGINX

nginx -t || die "nginx config test failed"
systemctl enable nginx >/dev/null
systemctl reload-or-restart nginx

if [ "$TLS" = "1" ]; then
  case "$mgr" in
    apt)     install_packages certbot python3-certbot-nginx ;;
    dnf|yum)
      [ "$(os_id)" != "fedora" ] && { install_packages epel-release || true; }
      install_packages certbot python3-certbot-nginx
      ;;
  esac
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL"
  log "TLS certificate obtained for $DOMAIN"
fi

log "nginx configured — public UI: ${SCHEME}://${DOMAIN}/"
log "                   sysop console: ${SCHEME}://${DOMAIN}/sysop"
[ "${#ADMIN_ALLOW[@]}" -gt 0 ] && log "                   admin IP allowlist enabled"
[ -n "$ADMIN_BASIC_AUTH" ] && log "                   admin basic auth enabled"
